// <auto-generated />
namespace HandIn2_2RDB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KeyAltAdress6 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KeyAltAdress6));
        
        string IMigrationMetadata.Id
        {
            get { return "201804022111108_KeyAltAdress6"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
